name: knue_moa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  html: ^0.15.4
  url_launcher: ^6.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  lucide_icons: ^0.257.0
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_staggered_animations: ^1.1.0
  # --- 추가된 패키지 ---
  google_generative_ai: ^0.2.0 # Gemini API
  share_plus: ^7.2.1 # 지원서 공유
  uuid: ^4.3.3 # 고유 ID 생성
  euc: ^1.0.6+8
  cp949_codec: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true